# Generated by Django 5.2.14 on 2026-06-11 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fsm', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assigned_worker',
        ),
        migrations.RemoveField(
            model_name='job',
            name='base_pay',
        ),
        migrations.RemoveField(
            model_name='job',
            name='client_rate',
        ),
        migrations.AddField(
            model_name='job',
            name='account_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_jobs', to='organizations.workerprofile'),
        ),
        migrations.AddField(
            model_name='job',
            name='additional_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='job',
            name='client_given_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='job',
            name='client_rate_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('hourly', 'Hourly')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='client_tip',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='job',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='job',
            name='entrance_instructions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='finance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='frequency',
            field=models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('bi_weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='one_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='material_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='qc_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='service_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(choices=[('flat', 'Flat Rate'), ('hourly', 'Hourly')], default='flat', max_length=10)),
                ('pay_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tip_split', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('is_primary_worker', models.BooleanField(default=False)),
                ('clocked_in_at', models.DateTimeField(blank=True, null=True)),
                ('clocked_out_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='fsm.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='organizations.workerprofile')),
            ],
            options={
                'unique_together': {('job', 'worker')},
            },
        ),
    ]
