# Generated by Django 5.2.14 on 2026-06-17 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_property_unit_number_alter_property_address'),
        ('fsm', '0002_remove_job_assigned_worker_remove_job_base_pay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='entrance_instructions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='material_info',
        ),
        migrations.RemoveField(
            model_name='job',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='qc_instructions',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service_type',
        ),
        migrations.AddField(
            model_name='job',
            name='commission_type',
            field=models.CharField(choices=[('flat', 'Flat Amount ($)'), ('percent', 'Percentage (%)')], default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='The saved card to charge for this job.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='job',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='This job cannot start until the blocked job is completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks_jobs', to='fsm.job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location_address',
            field=models.CharField(blank=True, help_text='OVERRIDE: Leave blank to use the Property address. Only use for ad-hoc locations.', max_length=255),
        ),
        migrations.CreateModel(
            name='JobEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='evidence/%Y/%m/%d/')),
                ('captured_at', models.DateTimeField()),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_verified', models.BooleanField(default=False)),
                ('qc_notes', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='fsm.job')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='fsm.jobtask')),
            ],
        ),
    ]
