import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('crm', '0005_expand_phone_fields'),
        ('fsm', '0003_remove_job_entrance_instructions_and_more'),
        ('organizations', '0004_workspace_roles_and_worker_profile'),
    ]

    operations = [
        migrations.AddField(model_name='job', name='completion_mode', field=models.CharField(choices=[('tasks', 'Complete each task'), ('project', 'Complete the whole project')], default='tasks', max_length=20)),
        migrations.AddField(model_name='job', name='require_location', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='job', name='arrival_radius_meters', field=models.PositiveIntegerField(default=250)),
        migrations.AddField(model_name='job', name='require_closeout_confirmation', field=models.BooleanField(default=True)),
        migrations.AddField(model_name='job', name='closeout_instruction', field=models.CharField(blank=True, default='Secure the property and confirm the site is closed.', max_length=255)),
        migrations.AddField(model_name='job', name='completion_contact', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_notifications', to='crm.contact')),
        migrations.AddField(model_name='job', name='completion_notification_method', field=models.CharField(choices=[('none', 'Do not notify'), ('email', 'Email'), ('sms', 'SMS'), ('both', 'Email and SMS')], default='none', max_length=10)),
        migrations.AddField(model_name='job', name='completion_message_override', field=models.TextField(blank=True)),
        migrations.AddField(model_name='job', name='completion_notification_queued_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='jobassignment', name='accepted_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='jobassignment', name='arrived_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='jobassignment', name='closeout_confirmed_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='jobassignment', name='work_completed_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='jobtask', name='requires_evidence', field=models.BooleanField(default=False)),
        migrations.AddField(model_name='jobtask', name='completion_notes', field=models.TextField(blank=True)),
        migrations.AddField(model_name='jobtask', name='completed_at', field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name='jobtask', name='completed_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_job_tasks', to='organizations.workerprofile')),
        migrations.AlterField(model_name='jobevidence', name='task', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='fsm.jobtask')),
        migrations.AlterField(model_name='jobevidence', name='photo', field=models.FileField(upload_to='evidence/%Y/%m/%d/')),
        migrations.AddField(model_name='jobevidence', name='media_type', field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
        migrations.AddField(model_name='jobevidence', name='uploaded_by', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_evidence', to='organizations.workerprofile')),
        migrations.AddField(model_name='jobevidence', name='note', field=models.TextField(blank=True)),
        migrations.CreateModel(
            name='FieldShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_shifts', to='organizations.workerprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_shifts', to='organizations.workspace')),
            ],
            options={'ordering': ('-started_at',)},
        ),
        migrations.CreateModel(
            name='FieldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('shift_started', 'Available for work'), ('shift_ended', 'Shift ended'), ('job_accepted', 'Job accepted'), ('arrived', 'Arrived at location'), ('work_started', 'Work started'), ('task_completed', 'Task completed'), ('note_added', 'Note added'), ('evidence_added', 'Evidence added'), ('closeout_confirmed', 'Closeout confirmed'), ('job_completed', 'Job completed')], max_length=30)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('note_original', models.TextField(blank=True)),
                ('note_english', models.TextField(blank=True)),
                ('source_language', models.CharField(blank=True, max_length=10)),
                ('translation_status', models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Pending'), ('translated', 'Translated'), ('failed', 'Failed')], default='not_needed', max_length=20)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_events', to='fsm.job')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_events', to='fsm.jobtask')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_events', to='organizations.workerprofile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_events', to='organizations.workspace')),
            ],
            options={'ordering': ('-occurred_at',)},
        ),
        migrations.CreateModel(
            name='CompletionNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(default='Your {{service}} is complete', max_length=200)),
                ('message_template', models.TextField(default='Dear {{first_name}},\n\nThank you for trusting us with {{service}}. Please check everything and let us know whether we exceeded your expectations. You may always reply to us.\n\nSincerely,\n{{workspace_name}}')),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('sms_from_number', models.CharField(blank=True, max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_notification_setting', to='organizations.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('recipient', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_notification_deliveries', to='fsm.job')),
            ],
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddConstraint(model_name='completionnotificationdelivery', constraint=models.UniqueConstraint(fields=('job', 'channel'), name='fsm_unique_completion_delivery_channel')),
    ]
