# Generated by Django 5.2.14 on 2026-07-24 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_crm_archive'),
        ('finance', '0002_platform_billing'),
        ('fsm', '0007_jobtask_assigned_worker'),
        ('organizations', '0010_platform_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='invoice',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='fsm.job'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.property'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.account'),
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('converted', 'Converted')], default='draft', max_length=20)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('external_source', models.CharField(blank=True, max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='crm.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='crm.contact')),
                ('converted_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_estimate', to='finance.invoice')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='fsm.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='organizations.workspace')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='crm.property')),
            ],
            options={
                'ordering': ('-issue_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='finance.estimate')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimated_items', to='fsm.job')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50)),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('paysimple', 'PaySimple'), ('zelle', 'Zelle'), ('pix', 'PIX'), ('check', 'Check'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('external_source', models.CharField(blank=True, max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_received', to='crm.account')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='organizations.workspace')),
            ],
            options={
                'ordering': ('-payment_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('next_issue_date', models.DateField()),
                ('due_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('line_items', models.JSONField(default=list)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_invoices', to='crm.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_invoices', to='fsm.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_invoices', to='organizations.workspace')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.property')),
            ],
            options={
                'ordering': ('next_issue_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WorkspacePaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('paysimple', 'PaySimple'), ('zelle', 'Zelle'), ('pix', 'PIX'), ('check', 'Check'), ('cash', 'Cash'), ('bank_transfer', 'Bank transfer'), ('other', 'Other')], max_length=30)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('is_enabled', models.BooleanField(default=False)),
                ('instructions', models.TextField(blank=True)),
                ('public_config', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='organizations.workspace')),
            ],
            options={
                'ordering': ('method',),
            },
        ),
        migrations.CreateModel(
            name='AccountingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('quickbooks', 'QuickBooks Online')], max_length=30)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('attention', 'Needs attention')], default='disconnected', max_length=20)),
                ('external_company_id', models.CharField(blank=True, max_length=120)),
                ('external_company_name', models.CharField(blank=True, max_length=160)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_direction', models.CharField(default='two_way', max_length=20)),
                ('sync_settings', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_connections', to='organizations.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'provider'), name='finance_unique_workspace_accounting_provider')],
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('applied', 'Applied'), ('void', 'Void')], default='draft', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('external_source', models.CharField(blank=True, max_length=40)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='crm.account')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='organizations.workspace')),
            ],
            options={
                'ordering': ('-issue_date', '-id'),
                'constraints': [models.UniqueConstraint(fields=('organization', 'credit_number'), name='finance_unique_workspace_credit_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='estimate',
            constraint=models.UniqueConstraint(fields=('organization', 'estimate_number'), name='finance_unique_workspace_estimate_number'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceived',
            constraint=models.UniqueConstraint(fields=('organization', 'payment_number'), name='finance_unique_workspace_payment_number'),
        ),
        migrations.AddConstraint(
            model_name='workspacepaymentoption',
            constraint=models.UniqueConstraint(fields=('workspace', 'method'), name='finance_unique_workspace_payment_option'),
        ),
    ]
