# Generated by Django 5.2.14 on 2026-06-10 05:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workspaces_workspace',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=50)),
                ('width', models.IntegerField(default=2)),
                ('height', models.IntegerField(default=2)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workspaces_dashboardwidget',
            },
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspaces', models.ManyToManyField(related_name='workers', to='organizations.workspace')),
            ],
            options={
                'db_table': 'workspaces_workerprofile',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='organizations.workspace')),
            ],
            options={
                'db_table': 'workspaces_skill',
            },
        ),
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active_zip_codes', models.JSONField(default=list)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_zones', to='organizations.workspace')),
            ],
            options={
                'db_table': 'workspaces_servicezone',
            },
        ),
        migrations.CreateModel(
            name='FormLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(max_length=50)),
                ('layout_json', models.JSONField(default=list)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_layouts', to='organizations.workspace')),
            ],
            options={
                'db_table': 'workspaces_formlayout',
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('internal_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Short Text'), ('textarea', 'Paragraph'), ('number', 'Number'), ('date', 'Date'), ('dropdown', 'Dropdown List'), ('boolean', 'Checkbox')], max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=False)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='organizations.workspace')),
            ],
            options={
                'db_table': 'workspaces_customfield',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('worker', 'Field Worker')], default='worker', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.workspace')),
            ],
            options={
                'db_table': 'workspaces_workspacemember',
            },
        ),
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.IntegerField(choices=[(1, 'Trainee / Helper'), (2, 'Secondary / Competent'), (3, 'Primary / Expert')], default=3)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_workers', to='organizations.skill')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='organizations.workerprofile')),
            ],
            options={
                'db_table': 'workspaces_workerskill',
                'unique_together': {('worker', 'skill')},
            },
        ),
    ]
