# Generated by Django 5.2.14 on 2026-06-11 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('last_four', models.CharField(max_length=4)),
                ('processor_token', models.CharField(blank=True, help_text='The token from Stripe/Authorize.net', max_length=255)),
                ('expiration_date', models.CharField(blank=True, help_text='MM/YYYY', max_length=7)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='crm.account')),
                ('assigned_property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cards', to='crm.property')),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
            },
        ),
    ]
