# Generated by Django 5.2.14 on 2026-06-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit_number',
            field=models.CharField(blank=True, help_text='Apt, Suite, Unit, or Building number', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(help_text='Street address, city, state (e.g., 1170 N Federal Hwy, Fort Lauderdale, FL)', max_length=255),
        ),
    ]
